# Generated by Django 5.1.4 on 2025-01-11 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_draft_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='desk_height',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
