# Generated by Django 5.1.4 on 2025-01-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_draft_desk_height_draft_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='desk_height',
        ),
    ]
