# Generated by Django 5.1.4 on 2025-01-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_draft_desk_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='body_height',
            field=models.FloatField(null=True),
        ),
    ]
