# Generated by Django 5.1.4 on 2025-01-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='thickness',
            field=models.FloatField(default=1.0),
        ),
    ]
